import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Inicio",
    link: "/",
  },
  {
    _id: 1002,
    title: "Tienda",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "Nosotros",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contacto",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Blog",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "202",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "203",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "204",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "205",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "206",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "207",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "208",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "209",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "210",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "211",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "212",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "213",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "214",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "215",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "216",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "217",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "219",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "220",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
  {
    _id: "221",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Playera oversize cómoda y moderna.",
    cat: "oversize",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "201",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "202",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },

  {
    _id: "203",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "2005",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },

  {
    _id: "20005",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },

  {
    _id: "206",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },

  {
    _id: "207",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },

  {
    _id: "208",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "233",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "220",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "221",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "215",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "216",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "209",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "210",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },

  {
    _id: "211",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "212",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "213",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "214",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },

  {
    _id: "217",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "219",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },

  // =================== imprimante hp =================

  {
    _id: "hp1",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },

  {
    _id: "hp2",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },

  {
    _id: "hp3",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  // =================== imprimante ricoh =================
  {
    _id: "ricoh1",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },

  {
    _id: "ricoh2",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "ricoh3",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "ricoh4",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
  {
    _id: "ricoh5",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },

  // =================== imprimante ricoh =================

  {
    _id: "espson1",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },

  {
    _id: "espson2",
    img: "https://starkbrand.com.co/cdn/shop/products/45_e68b75b1-02bc-47dc-81f3-9fcd3d98def9.jpg?v=1683307147&width=1125",
    productName: "Oversize",
    price: "85.00",
    color: "Blanco",
    badge: true,
    brand: "Limited Wear",
    des: "Playera oversize blanca, ideal para un look casual y cómodo. Confeccionada con materiales de alta calidad para mayor durabilidad.",
    cat: "oversize",
    pdf: "",
    ficheTech: [
      { label: "Material", value: "Algodón 100%" },
      { label: "Tamaño", value: "Unisex" },
      { label: "Color", value: "Blanco" },
      { label: "Estilo", value: "Oversize" },
      { label: "Lavado", value: "A máquina" },
      { label: "Peso", value: "200 g" },
      { label: "Cuello", value: "Redondo" },
      { label: "Manga", value: "Corta" },
    ],
  },
];
